### ISSUE TITLE
Support for SLO

### ISSUE THREAD

**Issue by ckoppelman** [megalus/django-google-sso#18]
Add support for Single Logout.  That is, Press Logout on Google logs you out of Django, and vice versa.

**Comment by chrismaille** [comment]
Hi! I like the idea for supoort SLO, but there's tons of traps here. My current thinking about this:

## Google Logout -> Django Logout
AFIK, you can logout from Google using the `https://accounts.google.com/logout` url (not sure if exists another way). In this case, django user session is still valid for up to  `GOOGLE_SSO_SESSION_COOKIE_AGE ` seconds (default: 1 hour).

So, to logout this user next time he tries to access any protected route in your Django project, the best way is to add a middleware to check current google user using the access token generated during login. Something like this:

```python
import httpx

def is_user_valid(token):
    headers = {
        'Authorization': f'Bearer {token}',
    }
    url = 'https://www.googleapis.com/oauth2/v3/userinfo'
    response = httpx.get(url, headers=headers)

    result = ... # Check some info and/or if this access token was revoked
    return result

class GoogleSLOMiddlewareExample:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        token = request.session.get('google_sso_access_token')

        if token and not is_user_valid(token):
            logout(request)

        response = self.get_response(request)
        return response
```
```python
# settings.py
MIDDLEWARE = [
    ...,
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "example_app.backend.GoogleSLOMiddlewareExample",  # Must be after AuthenticationMiddleware
]
```

To make this possible I'm adding a new configuration on 3.1: `GOOGLE_SSO_SAVE_ACCESS_TOKEN` which will save the access token generated during login inside request user session. (`request.session['google_sso_access_token']`)

But it's fair to say, this is a very simple solution.

## Django Logout -> Google Logout
I believe you can create a custom logout view, redirect the user to the Google Logout URL after logout in django. Something like this:

```python
from django.contrib.auth import logout
from django.http import HttpResponseRedirect

def single_logout_view(request):
    logout(request)
    return HttpResponseRedirect('https://accounts.google.com/logout')
```

**Comment by ckoppelman** [comment]
I meant that logging out of Google should log you out of Django, but I can see a use case for either direction.  Google, as Identity Provider, should provide a hook for that, but I'm not sure what the payload looks like and I can't find any documentation around it.
