### ISSUE TITLE
Support for saving all users as staff

### ISSUE THREAD

**Issue by engellee** [megalus/django-google-sso#22]
Hello from Cape Town, South Africa.

Thank you for your time.

Is there a mechanism to allow _all_ users to be created as staff. The requirement I have is that all staff members have access to the admin interface.

This could be achieved with a`GOOGLE_SSO_` setting?

Thanks again!

**Comment by chrismaille** [comment]
Hi @engellee,

I believe you can [fine tune your user](https://megalus.github.io/django-google-sso/users/#fine-tuning-users-before-login), like this:

In a new file add the hook:
```python
# your_django_app/hooks.py
from django.conf import settings

def pre_login_user(user, request):
    user_domain = user.email.split("@")[-1]
    if user_domain in settings.GOOGLE_SSO_ALLOWABLE_DOMAINS:
        user.is_staff = True
        user.save()
```

then add the configuration in settings:

```python
# settings.py
GOOGLE_SSO_PRE_LOGIN_CALLBACK = "your_django_app.hooks.pre_login_user"
```

Let me know if this helps you.

**Comment by engellee** [comment]
> 
> Let me know if this helps you.

Thanks so much. The hook worked great.
