### ISSUE TITLE
GOOGLE_SSO_LOGO_URL points at non-existing image

### ISSUE THREAD

**Issue by blueyed** [megalus/django-google-sso#28]
The URL for the Google logo defined at https://github.com/megalus/django-google-sso/blob/22f87bcfd56d4a2158da45ccef8c459e0e619a80/django_google_sso/conf.py#L43 results in a 404 error:
https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png

On https://about.google/brand-resource-center/logos-list/ it links to https://lh3.googleusercontent.com/COxitqgJr1sJnIDe8-jiKhxDx1FrYbtRHKJ9z_hELisAlapwE9LUPh6fcXIfb5vwpbMl4xl9H9TRFPc5NOO8Sb3VSgIBrfRYvW6cUA - maybe that could be used as a default?

**Comment by chrismaille** [comment]
Hi @blueyed , please check if the new version fixes this. Thanks for report!

**Comment by blueyed** [comment]
Yes, fixed.  Thanks!

ref: https://github.com/megalus/django-google-sso/commit/7212d2c30a25710a507ed26e5640284bd8e87486#diff-c2cc7298bc96c6d7bde975f77bca14ebd783ff2e3c8636910ce1584a0f1bdb5aL43-R47
