### ISSUE TITLE
KeyError: 'locale' - Google userinfo API not always returning locale（Python < 3.10）

### ISSUE THREAD

**Issue by jkkitakita** [megalus/django-google-sso#34]
Hi @chrismaille,

Issue similar to https://github.com/megalus/django-google-sso/issues/31.

I am using Python 3.9, in which case I need to use v3.3.0.
However, this issue prevents me from using v3.3.0.
I would like to fix v3.3.0. What should I do?

**Comment by chrismaille** [comment]
Hi @jkkitakita ,

Thanks for the contact. Best way is to change, in your fork, inside module `django_google_sso/main.py`, the methods  `GoogleSSOUser.objects.update_or_create` at lines 116/117 and `check_for_update` at lines 126/127.

The fix commit to reference:  https://github.com/megalus/django-google-sso/commit/646d986d609aba7acc4f0df0ea0f6136a4fe7747#diff-11b18460ec9910348ab3eb7a944e682588b85cd7047922cf54d3aab72ad882b9L116

Please let me know if this help you.

**Comment by jkkitakita** [comment]
@chrismaille 
Thanks for your reply!
I will fork and try to fix it. I will try to deal with other cases than this issue as well.
I will also make sure to raise the Python version to 3.10 or higher.
