### ISSUE TITLE
KeyError: 'locale'

### ISSUE THREAD

**Issue by MohanReddy999** [megalus/django-google-sso#38]
https://megalus.github.io/django-google-sso/settings/

Even after setting `GOOGLE_SSO_DEFAULT_LOCALE = "en" `in **settings.py** as per the documentation, I am still encountering an error during SSO login.

at line `django_google_sso/main.py", line 118, in get_or_create_user`

<img width="411" alt="image" src="https://github.com/user-attachments/assets/454100cd-7322-41bd-bbbe-cff9f604c98e">

**Comment by chrismaille** [comment]
Hi @MohanReddy999, thanks for the contact. Can you please check what version of django-google-sso you're using? Latest version is 6.2.1.

If you are using the latest version, can you please kindly provided the logs from your application?
