### ISSUE TITLE
 Avoiding the creation of a GoogleSSOUser object.

### ISSUE THREAD

**Issue by Premium00** [megalus/django-google-sso#39]
Can I perform an additional operation before creating a GoogleSSOUser object?
I want to check if the user already exists in the database, and if they do, I don't want to create a GoogleSSOUser object or allow the user to log in.

**Comment by chrismaille** [comment]
Hi @Premium00 , thanks for the contact, i`ll add a new option on package: `GOOGLE_SSO_SAVE_BASIC_GOOGLE_INFO`, on next version. Please add to your settings.py:

```python
# settings.py
GOOGLE_SSO_SAVE_BASIC_GOOGLE_INFO = False
```
