### ISSUE TITLE
Conflict registering admin model

### ISSUE THREAD

**Issue by paulschreiber** [megalus/django-google-sso#41]
## Description
When I run `migrate`, I get this error:
```
  File "/app/terraso_backend/apps/core/admin.py", line 60, in <module>
    @admin.register(User)
     ^^^^^^^^^^^^^^^^^^^^
  File "/home/terraso/.local/lib/python3.12/site-packages/django/contrib/admin/decorators.py", line 107, in _model_admin_wrapper
    admin_site.register(models, admin_class=admin_class)
  File "/home/terraso/.local/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 125, in register
    raise AlreadyRegistered(msg)
django.contrib.admin.exceptions.AlreadyRegistered: The model User is already registered with 'core.GoogleSSOUserAdmin'.
```

We already have a `User` model for our app:
https://github.com/techmatters/terraso-backend/blob/main/terraso_backend/apps/core/admin.py

The workaround was to make sure `"django_google_sso",` was at the end of `INSTALLED_APPS`.

**Comment by chrismaille** [comment]
Hi @paulschreiber , thanks for the message. I'll look into it.

**Comment by chrismaille** [comment]
Looking at the code, can you try this?

```python
# terraso_backend/apps/core/admin.py
from django_google_sso.admin import (
    GoogleSSOInlineAdmin, get_current_user_and_admin
)

CurrentUserModel, last_admin, LastUserAdmin = get_current_user_and_admin()

if admin.site.is_registered(CurrentUserModel):
    admin.site.unregister(CurrentUserModel)

@admin.register(CurrentUserModel)  # <-- Change here
class UserAdmin(LastUserAdmin):  # <-- Change here
    ordering = ("email",)
    list_display = ("email", "first_name", "last_name", "created_at", "is_staff")
    search_fields = ("email", "first_name", "last_name")
    inlines = (UserPreferenceInline, GoogleSSOInlineAdmin)  # <-- Add GoogleSSOInlineAdmin here
    ...
```

The `get_current_user_and_admin` helper retrieve the last Admin and User model registered in Django. I think thats why when you put the package at the end of INSTALLED_APPS, it works, because this helper (which we use too) finds the `UserAdmin` you registered before.

**Comment by hbruno** [comment]
I confirm that importing the library at the end of the installed apps solve this problem.
In my project I used 

``` 
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS + ['django_google_sso']
```

**Comment by chrismaille** [comment]
Both solutions work, but my advice is to unregister and register again the custom User Admin class, which is in pair with this [document](https://docs.djangoproject.com/en/5.1/topics/auth/customizing/#extending-the-existing-user-model). You can do this manually, use the `get_current_user_and_admin` helper as stated in the [docs](https://megalus.github.io/django-google-sso/admin/), or add the package at the end of your `INSTALLED_APPS`. I'll include this on the documentation.
