### ISSUE TITLE
How to perform a validation at pre create callback?

### ISSUE THREAD

**Issue by mrsarm** [megalus/django-google-sso#43]
BTW awesome project !

I want to do something like this:

```py
def pre_create_callback(google_info, request) -> dict | None:
    if not google_info.get('verified_email'):
        raise ValidationError('User email is not verified.')
    # move forward with the sign-up ...
```

The problem is, an ugly error page with a stack trace is shown, and in non debug mode the error is not even visible to the user. Is there a way to redirect to the user back to the login page and show why the signup was not allowed?

The most close I get is, before raising the exception, do this:

```py
from django.contrib import messages

def pre_create_callback(google_info, request) -> dict | None:
    if not google_info.get('verified_email'):
        messages.error(request, "User email is not verified.")    # <-- Message
        raise ValidationError('User email is not verified.')
    # move forward with the sign-up ...
```

An the error is indeed shown in the login page once the user goes back, but not before seeing the error page, and only if the user goes back entering the URL again, or using the browser history.

**Comment by mrsarm** [comment]
BTW, the `verified_email` check is just an example, the idea is to make a more custom made validation involving calls to external services to see whether to grant the user access to the system or not upon creation.

**Comment by chrismaille** [comment]
Hi, @mrsarm, thanks for the contact.

You got a very good point. I'm pushing a new version adding the option `GOOGLE_SSO_PRE_VALIDATE_CALLBACK` you can use to create your custom validation:

```python
# settings.py
GOOGLE_SSO_PRE_VALIDATE_CALLBACK="my_hooks.my_custom_validation"
```

```python
# my_hooks.py

def my_custom_validation(google_info, request):
    # Process here
    return True  # return the boolean if user can be created or not
```

Please note, if even you return `true` here, the package can denied creation if the email is not valid.

Please let me know if this helps. New version is 6.5.0.

**Comment by mrsarm** [comment]
ooh sounds good ! going to try right now...

**Comment by mrsarm** [comment]
Hey, thanks for the patch ! worked well. My code looks like the following:

```py
def pre_validate_callback(google_info, request) -> bool:
    if <MY VALIDATIONS>:
        messages.error(request, "I don't like this guy.")
        return False
    return True
```

It works. The only thing is, when my error is shown, another error that I think was meant for other validations (email validations) are added to the error section in the login:

![Django Google SSO Validation Error](https://github.com/user-attachments/assets/636d1f55-959b-4639-952b-062e88ce37f5)

I would rather only show the errors set in `pre_validate_callback`. The reason is because the redirect to the error page (that by default is the same login page) is done either if the email is not valid or the pre validation fail, but the logic in the code does not make any distinction between the two.

Anyway, it's fine.

**Comment by chrismaille** [comment]
Indeed, the `Email address not allowed` is a catch-all message intended for failed attempts without give any context about the motive. This message exists for anyone who did not create your own custom validation logic.

If you want to give more context why you're deny the login, please be aware for possible reverse-enginering of the denial logic using the information you gave.

I'll close the issue, but feel free to reopen if you need 👍🏾
