### ISSUE TITLE
KeyError at /google_sso/callback/

### ISSUE THREAD

**Issue by khraina** [megalus/django-google-sso#46]
KeyError
'locale'
D:\google sso\env\lib\site-packages\django_google_sso\main.py, line 116, in get_or_create_user
django_google_sso.views.callback
D:\google sso\env\Scripts\python.exe
3.9.11
['D:\\google sso\\django-auth\\elevate',  'C:\\Users\\Dell\\AppData\\Local\\Programs\\Python\\Python39\\python39.zip',  'C:\\Users\\Dell\\AppData\\Local\\Programs\\Python\\Python39\\DLLs',  'C:\\Users\\Dell\\AppData\\Local\\Programs\\Python\\Python39\\lib',  'C:\\Users\\Dell\\AppData\\Local\\Programs\\Python\\Python39',  'D:\\google sso\\env',  'D:\\google sso\\env\\lib\\site-packages']

**Comment by chrismaille** [comment]
Hi @khraina, thanks for the message. You need to update to the most recent version. More context here: https://github.com/megalus/django-google-sso/issues/34

Please let me know if this helps.
